### ISSUE TITLE
rgmat function appear in doc

### ISSUE THREAD

**Issue by gherardovarando** [irenecrsn/gmat#3] opened 2018-11-06 13:42 UTC
From the documentation it seems there exist a function called ``rgmat`` . 
I think the guilty line is more or less [here](https://github.com/irenecrsn/gmat/blob/b8570e3736b49c11cffc7d696193e02d2e7654bb/R/functions.R#L6)

**Comment by irenecrsn** [comment] 2018-11-06 16:07
OK, this is not a bug, `rgmat` is the name given to the "group" of documentation of both `port` and `diagdom`. However, we could use a more descriptive name instead of `rgmat`.

**Comment by irenecrsn** [comment] 2018-11-07 11:45
Let me know if you like the new name, so I can close this issue, or either propose a new one if you think of another description that fits better.

**Comment by gherardovarando** [comment] 2018-11-13 12:15
I agree with new name.

**Closed** 2018-11-14 10:11 UTC
Labels: doc, enhancement
